"""
.

Revision ID: 62dc6e87a392
Revises: 000000000000
Create Date: 2025-03-30 15:38:18.814166+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62dc6e87a392'
down_revision: str | None = '000000000000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_uuid', sa.String(length=100), nullable=True))
    op.add_column('videos', sa.Column('parts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'parts_count')
    op.drop_column('videos', 'video_uuid')
    # ### end Alembic commands ###