services:
  server:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"

    env_file: .env


    user: server

    stop_signal: SIGINT

    depends_on:
      - database
     # - caddy


    restart: always

    entrypoint: [ "python", "-m", "server" ]

  database:
    image: postgres:17.4
    shm_size: 1gb

    environment:
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
      - POSTGRES_DB=$PSQL_DB


    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./psql/db-init-scripts:/docker-entrypoint-initdb.d:ro

    restart: always
  blob-bridge:
    build:
      context: ./blob-bridge
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - PORT=3001
      - FASTAPI_URL=http://server:8000
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
    depends_on:
      - server
    restart: always
    volumes:
      - ./blob-bridge/logs:/app/logs

#  caddy:  # Uncomment if you want to use Caddy as a reverse proxy
#    image: caddy:2.9.1
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#       - ./caddy/Caddyfile:/etc/caddy/Caddyfile
#       - ./caddy/data:/data
#       - ./caddy/config:/config
#       # - ./caddy/public:/usr/share/caddy/
#       - ./front-end:/usr/share/caddy
#    restart: always




